# Generated by Django 5.0.4 on 2024-04-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LowerSchoolStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('currentClass', models.CharField(choices=[('nursery', 'Nursery'), ('preK', 'Pre-K'), ('firstGrade', 'First Grade'), ('secondGrade', 'Second Grade'), ('thirdGrade', 'Third Grade')], max_length=20)),
                ('parentName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('emergencyContact', models.CharField(max_length=15)),
                ('subjectsRequired', models.TextField()),
                ('interests', models.TextField(blank=True, null=True)),
                ('expectations', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
