# Generated by Django 5.0.4 on 2024-04-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0004_alter_highschoolstudent_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highschoolstudent',
            old_name='current_class',
            new_name='currentClass',
        ),
        migrations.RenameField(
            model_name='highschoolstudent',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='highschoolstudent',
            old_name='emergency_contact',
            new_name='emergencyContact',
        ),
        migrations.RenameField(
            model_name='highschoolstudent',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='highschoolstudent',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='highschoolstudent',
            old_name='parent_name',
            new_name='parentName',
        ),
        migrations.RenameField(
            model_name='highschoolstudent',
            old_name='subjects_required',
            new_name='subjectsRequired',
        ),
    ]
