# Generated by Django 5.0.4 on 2024-04-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0006_rename_academic_goals_middleschoolstudent_academicgoals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('agree', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
