# Generated by Django 5.0.4 on 2024-04-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0008_remove_contact_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='agree',
        ),
    ]
